import { it, expect, vi } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createServer } from '../src/tools/index.js';
import { LearnUsClient } from '../src/client/LearnUsClient.js';
import { PlaywrightAuthManager } from '../src/auth/PlaywrightAuthManager.js';
it('exposes read-only tools over MCP and contains provider failures', async () => {
  const auth = new PlaywrightAuthManager({getCredentials:async () => {throw Error('synthetic-private-password');}});
  const learnus = new LearnUsClient(auth);
  const getCourse = vi.spyOn(learnus,'getCourse').mockResolvedValue({name:'Synthetic',activities:[]});
  const getAssignment = vi.spyOn(learnus,'getAssignment').mockResolvedValue({cmid:12,url:'https://ys.learnus.org/mod/assign/view.php?id=12',extraFields:[],warnings:[]});
  const upcoming = vi.spyOn(learnus,'upcoming').mockResolvedValue({events:[],warnings:[],truncated:false});
  const announcements = vi.spyOn(learnus,'listAnnouncements').mockResolvedValue({items:[],warnings:['NO_ANNOUNCEMENTS_FOUND'],diagnostics:{courseCount:1,announcementWidgetCount:1,emptyCourseCount:1,boardCount:1,boardRequestCount:1,announcementCount:0,parserMismatchCount:0}});
  const announcement = vi.spyOn(learnus,'getAnnouncement').mockResolvedValue({item:{id:'21',moduleId:'11',title:'Synthetic',url:'https://ys.learnus.org/mod/ubboard/article.php?id=11&bwid=21'},warnings:[]});
  const notifications = vi.spyOn(learnus,'listNotifications').mockResolvedValue({items:[],warnings:['NO_NOTIFICATIONS_FOUND']});
  const videos = vi.spyOn(learnus,'listVideos').mockResolvedValue({items:[],currentWeek:2,warnings:[]});
  const attendance = vi.spyOn(learnus,'getVideoAttendance').mockResolvedValue({mode:'progress' as const,items:[],currentWeek:2,warnings:[]});
  const overview = vi.spyOn(learnus,'learningOverview').mockResolvedValue({asOf:'2026-09-08T00:00:00.000Z',currentWeek:2,courses:[],requiredIncomplete:[],completed:[],excludedOrOptional:[],unknown:[],warnings:[]});
  const files = vi.spyOn(learnus,'listFiles').mockResolvedValue({items:[],warnings:[]});
  const download = vi.spyOn(learnus,'downloadFile').mockResolvedValue({fileId:'123e4567-e89b-12d3-a456-426614174000',path:'C:/tmp/test.pdf',sizeBytes:2,mimeType:'application/pdf'});
  const aggregate = vi.spyOn(learnus,'getOverview').mockResolvedValue({range:{from:'2026-09-09',to:'2026-09-15'},warnings:[]});
  const server = createServer(learnus);
  const client = new Client({name:'test',version:'1'});
  const [a,b] = InMemoryTransport.createLinkedPair();
  await server.connect(a); await client.connect(b);
  try {
    const list = await client.listTools();
    expect(client.getServerVersion()?.description).toContain('Primary MCP interface');
    expect(list.tools.find(t=>t.name==='learnus_get_overview')?.description).toContain('generic personal to-do/calendar');
    expect(list.tools.find(t=>t.name==='learnus_auth_status')?.description).toContain('as a prerequisite');
    expect(list.tools.map(t => t.name)).toEqual(['learnus_auth_status','learnus_list_courses','learnus_get_course','learnus_list_activities','learnus_get_assignment','learnus_upcoming','learnus_list_announcements','learnus_get_announcement','learnus_list_notifications','learnus_list_videos','learnus_get_video_attendance','learnus_get_learning_overview','learnus_list_files','learnus_download_file','learnus_get_overview','learnus_get_weekly_tasks']);
    const weekly=list.tools.find(t=>t.name==='learnus_get_weekly_tasks')!;
    expect(weekly.annotations).toMatchObject({readOnlyHint:true,idempotentHint:true,destructiveHint:false});
    expect(weekly.description).toContain('unrelated personal to-do/calendar');
    expect(weekly.description).toContain('even without the words LearnUs/런어스');
    expect(client.getInstructions()).toContain('prefer learnus_get_weekly_tasks');
    expect(client.getInstructions()).toContain('primary authoritative interface');
    expect(client.getInstructions()).toContain('AUTH_CHALLENGE_REQUIRED');
    expect(client.getInstructions()).toContain('Never silently switch to Browser');
    expect(client.getInstructions()).toContain('empty results');
    expect(list.tools.filter(t=>t.name!=='learnus_download_file').every(t=>!t.description?.includes('Browser fallback'))).toBe(true);
    expect(client.getInstructions()).toContain('Browser/Computer Use is allowed only');
    expect(list.tools.find(t=>t.name==='learnus_get_assignment')?.description).toContain('submission/grading status');
    expect(list.tools.find(t=>t.name==='learnus_list_files')?.description).toContain('course materials, PDFs and attachments');
    expect(list.tools.find(t=>t.name==='learnus_get_video_attendance')?.description).toContain('attendance target and attendance status');
    expect(list.tools.find(t=>t.name==='learnus_list_notifications')?.description).toContain('without marking them read');
    expect(list.tools.find(t=>t.name==='learnus_get_course')?.inputSchema.properties.courseId.description).toContain('Exact Moodle course ID');
    expect(list.tools.find(t=>t.name==='learnus_upcoming')?.inputSchema.properties.from.description).toContain('Inclusive range start');
    expect(list.tools.find(t=>t.name==='learnus_list_files')?.inputSchema.properties.scope.description).toContain('Where to discover files');
    for (const tool of list.tools) {
      const courseId=tool.inputSchema.properties?.courseId;
      if(courseId) expect(courseId).toMatchObject({type:'string',pattern:'^[1-9]\\d*$',description:'Exact Moodle course ID returned by a LearnUs course tool.'});
    }
    expect(list.tools.filter(t=>t.name!=='learnus_download_file').every(t => t.annotations?.readOnlyHint)).toBe(true);
    expect(list.tools.find(t=>t.name==='learnus_download_file')?.annotations?.readOnlyHint).toBe(false);
    const status = await client.callTool({name:'learnus_auth_status',arguments:{}});
    expect(JSON.stringify(status)).toContain('authenticated');
    const failure = await client.callTool({name:'learnus_list_courses',arguments:{}});
    expect(failure.isError).toBe(true);
    expect(JSON.stringify(failure)).not.toContain('synthetic-private-password');
    const course = await client.callTool({name:'learnus_get_course',arguments:{courseId:'11'}});
    expect(course.isError).not.toBe(true);
    expect(getCourse).toHaveBeenCalledExactlyOnceWith(11);
    const invalid = await client.callTool({name:'learnus_get_course',arguments:{courseId:'0'}});
    expect(invalid.isError).toBe(true);
    expect(getCourse).toHaveBeenCalledTimes(1);
    for (const name of ['learnus_get_course','learnus_list_activities','learnus_upcoming']) {
      expect((await client.callTool({name,arguments:{courseId:11}})).isError).toBe(true);
    }
    expect(getCourse).toHaveBeenCalledTimes(1);
    expect(upcoming).not.toHaveBeenCalled();
    const activities = await client.callTool({name:'learnus_list_activities',arguments:{courseId:'11'}});
    expect(activities.isError).not.toBe(true);
    expect(JSON.stringify(activities)).toContain('activities');
    const assignment = await client.callTool({name:'learnus_get_assignment',arguments:{cmid:12}});
    expect(assignment.isError).not.toBe(true);
    expect(getAssignment).toHaveBeenCalledExactlyOnceWith(12);
    const invalidAssignment = await client.callTool({name:'learnus_get_assignment',arguments:{cmid:0}});
    expect(invalidAssignment.isError).toBe(true);
    expect(getAssignment).toHaveBeenCalledTimes(1);
    const events = await client.callTool({name:'learnus_upcoming',arguments:{from:'2026-09-01',to:'2026-10-01',courseId:'7'}});
    expect(events.isError).not.toBe(true);
    expect(upcoming).toHaveBeenCalledExactlyOnceWith({from:'2026-09-01',to:'2026-10-01',limit:20,courseId:7});
    const announcementList = await client.callTool({name:'learnus_list_announcements',arguments:{courseId:'7'}});
    expect(announcementList.isError).not.toBe(true);
    expect(JSON.parse((announcementList.content as {text:string}[])[0].text)).toEqual({items:[],warnings:['NO_ANNOUNCEMENTS_FOUND']});
    expect(announcements).toHaveBeenCalledExactlyOnceWith({courseId:'7',limit:10});
    expect((await client.callTool({name:'learnus_get_announcement',arguments:{moduleId:'11',articleId:'21'}})).isError).not.toBe(true);
    expect(announcement).toHaveBeenCalledExactlyOnceWith('11','21');
    expect((await client.callTool({name:'learnus_list_notifications',arguments:{}})).isError).not.toBe(true);
    expect(notifications).toHaveBeenCalledExactlyOnceWith({limit:10});
    expect((await client.callTool({name:'learnus_get_announcement',arguments:{moduleId:'11&delete=1',articleId:'21'}})).isError).toBe(true);
    expect(announcement).toHaveBeenCalledTimes(1);
    expect((await client.callTool({name:'learnus_list_videos',arguments:{courseId:'7'}})).isError).not.toBe(true);
    expect(videos).toHaveBeenCalledExactlyOnceWith({courseId:'7'});
    expect((await client.callTool({name:'learnus_get_video_attendance',arguments:{courseId:'7'}})).isError).not.toBe(true);
    expect(attendance).toHaveBeenCalledExactlyOnceWith({courseId:'7'});
    expect((await client.callTool({name:'learnus_get_learning_overview',arguments:{courseId:'7',week:'current'}})).isError).not.toBe(true);
    expect(overview).toHaveBeenCalledExactlyOnceWith({courseId:'7',week:'current'});
    expect((await client.callTool({name:'learnus_list_files',arguments:{courseId:'7',scope:'course'}})).isError).not.toBe(true);
    expect(files).toHaveBeenCalledExactlyOnceWith({courseId:'7',scope:'course'});
    expect((await client.callTool({name:'learnus_download_file',arguments:{fileId:'123e4567-e89b-12d3-a456-426614174000'}})).isError).not.toBe(true);
    expect(download).toHaveBeenCalledExactlyOnceWith('123e4567-e89b-12d3-a456-426614174000');
    expect((await client.callTool({name:'learnus_get_overview',arguments:{courseId:'7',includeAssignments:false}})).isError).not.toBe(true);
    expect(aggregate).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({courseId:7,includeAssignments:false,maxItemsPerSection:10}));
    aggregate.mockClear();
    expect((await client.callTool({name:'learnus_get_weekly_tasks',arguments:{courseId:'7'}})).isError).not.toBe(true);
    expect(aggregate).toHaveBeenCalledExactlyOnceWith({courseId:7,includeLearning:true});
    expect((await client.callTool({name:'learnus_get_weekly_tasks',arguments:{courseId:'7&delete=1'}})).isError).toBe(true);
    expect(aggregate).toHaveBeenCalledTimes(1);
  } finally { await client.close(); await server.close(); await auth.close(); }
});
